services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: evoting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d evoting_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - rsa_keys:/app/app/keys
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  rsa_keys:
