from enum import Enum


class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    HASH_MISMATCH = "HASH_MISMATCH"
    DECRYPTION_FAILED = "DECRYPTION_FAILED"
    MALFORMED_PLAINTEXT = "MALFORMED_PLAINTEXT"


class AuditEventType(str, Enum):
    VOTE_CAST = "VOTE_CAST"
    DOUBLE_VOTE_ATTEMPT = "DOUBLE_VOTE_ATTEMPT"
    INVALID_SIGNATURE_DETECTED = "INVALID_SIGNATURE_DETECTED"
    HASH_MISMATCH_DETECTED = "HASH_MISMATCH_DETECTED"
    DECRYPTION_FAILED = "DECRYPTION_FAILED"
    MALFORMED_PLAINTEXT = "MALFORMED_PLAINTEXT"
    RECAPITULATION_STARTED = "RECAPITULATION_STARTED"
    RECAPITULATION_COMPLETED = "RECAPITULATION_COMPLETED"
